{{- if .Values.kubecostProductConfigs }}
{{- if .Values.kubecostProductConfigs.createServiceKey }}
{{- if eq .Values.kubecostProductConfigs.createdServiceKeyType "AZURE" }}
apiVersion: v1
kind: Secret
metadata:
  name: cloud-service-key
type: Opaque
stringData:
  service-key.json: |-
    {
      "subscriptionId": "{{ .Values.kubecostProductConfigs.azureSubscriptionID }}",
      "serviceKey": {
        "appId": "{{ .Values.kubecostProductConfigs.azureClientID }}",
        "password": "{{ .Values.kubecostProductConfigs.azureClientPassword }}",
        "tenant": "{{ .Values.kubecostProductConfigs.azureTenantID }}"
      }
    }
{{- end -}}
{{- end -}}
{{- end -}}
