{{- if .Values.remoteWrite -}}
{{- if .Values.remoteWrite.postgres -}}
{{- if .Values.remoteWrite.postgres.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "cost-analyzer.fullname" . }}-adapter
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: adapter
    spec:
      initContainers:
        - name: kubecost-sql-init
          image: ajaytripathy/kubecost-sql-init:prod-{{ $.Chart.AppVersion }}
          imagePullPolicy: Always
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "cost-analyzer.fullname" . }}
                  key: prometheus-server-endpoint
      containers:
          - image: timescale/prometheus-postgresql-adapter:latest
            name: pgprometheusadapter
            ports:
              - containerPort: 9201
            args:
            {{- if .Values.remoteWrite.postgres.installLocal }}
              - "-pg-host=pgprometheus"
            {{- else }}
              - "-pg-host={{ .Values.remoteWrite.postgres.remotePostgresAddress }}"
            {{- end }}
              - "-pg-prometheus-log-samples=true"
              - "-pg-password={{ .Values.remoteWrite.postgres.auth.password }}"
{{- end }}
{{- end }}
{{- end }}