{{- $serviceName := include "cost-analyzer.serviceName" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  nginx.conf: |
    gzip_static  on;

    upstream api {
        server {{ $serviceName }}.{{ .Release.Namespace }}:9001;
    }

    upstream model {
        server {{ $serviceName }}.{{ .Release.Namespace }}:9003;
    }

{{- if and .Values.turndown .Values.turndown.enabled }}
    upstream turndown {
        server {{ template "kubecost.turndownName" . }}-service.{{ .Release.Namespace }}:9731;
    }
{{- end }}

{{- if .Values.global.grafana.proxy }}
    upstream grafana {
{{- if .Values.global.grafana.enabled }}
        server {{ .Release.Name }}-grafana.{{ .Release.Namespace }};
{{ else }}
        server {{.Values.global.grafana.domainName}};
{{ end }}
    }
{{ end }}

    server {
        listen 9090;
        server_name _;
        root /var/www;
        index index.html;
        add_header Cache-Control "max-age=300";
        add_header Cache-Control "must-revalidate";
        add_header ETag "{{ $.Chart.Version }}";
        add_header 'Access-Control-Allow-Origin' * always;

        location /api/ {
            proxy_pass http://api/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /model/ {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://model/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
{{- if and .Values.turndown .Values.turndown.enabled }}
        location /turndown/ {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://turndown/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
{{- end }}
        location /saml/ {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://model/saml/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /login {
            proxy_connect_timeout       180;
            proxy_send_timeout          180;
            proxy_read_timeout          180;
            proxy_pass http://model/login;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }

{{- if .Values.global.grafana.proxy }}
        location /grafana/ {
            proxy_pass http://grafana/;
            proxy_redirect off;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        }
{{ end }}
    }
