apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    app: cost-analyzer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{- if .Values.global.prometheus.enabled }}
    prometheus-alertmanager-endpoint: http://{{ .Release.Name }}-prometheus-alertmanager.{{ .Release.Namespace  }}.svc.cluster.local
  {{ else }}
<<<<<<< Updated upstream
    prometheus-alertmanager-endpoint: {{ .Values.global.notifications.alertmanager.fqdn }}
=======
    prometheus-alertmanager-endpoint: {{ .Values.global.prometheus.alertmanager.fqdn }}
>>>>>>> Stashed changes
  {{- end -}}
  {{- if .Values.global.prometheus.enabled }}
    prometheus-server-endpoint: http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace  }}.svc.cluster.local
  {{ else }}
    prometheus-server-endpoint: {{ .Values.global.prometheus.fqdn }}
  {{- end -}}
