{{- if .Values.alertConfigs }}
{{- if .Values.alertConfigs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-configs
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  alerts.json: '{{ toJson .Values.alertConfigs }}'
{{- end -}}
{{- end -}}
