apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    app: cost-analyzer
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cost-analyzer
    spec:
      restartPolicy: Always
      serviceAccountName: {{ template "cost-analyzer.fullname" . }}
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: default.conf
        - name: persistent-configs
          persistentVolumeClaim: 
            claimName: {{ template "cost-analyzer.fullname" . }}
      containers:
        - image: ajaytripathy/kubecost-frontend:latest
          name: cost-analyzer-frontend
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
        - image: 'ajaytripathy/kubecost:latest'
          name: cost-analyzer-server
          volumeMounts:
            - name: persistent-configs
              mountPath: /var/configs
          env:
            - name: PROMETHEUS_SERVER_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ template "cost-analyzer.fullname" . }}
                  key: prometheus-server-endpoint
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/configs/key.json
          resources:
            requests:
              cpu: 10m
              memory: 55M
          imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
