{{- if .Values.networkCosts.serviceMonitor }}
{{- if .Values.networkCosts.serviceMonitor.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.networkCostsName" . }}
  labels:
    {{ include "cost-analyzer.networkCostsSelectorLabels" . | nindent 4 }}
    {{- if .Values.networkCosts.serviceMonitor.additionalLabels }}
    {{ toYaml .Values.networkCosts.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    app: {{ template "cost-analyzer.networkCostsName" . }}
  type: ClusterIP
  ports:
    - name: metrics
      port: 3001
      targetPort: http-server
      protocol: TCP
{{- end }}
{{- end }}
