kind: Service
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  selector:
    app: cost-analyzer
  type: ClusterIP
  ports:
    - name: server
      port: 9001
      targetPort: 9001
    - name: model
      port: 9003
      targetPort: 9003
    - name: frontend
      port: 9090
      targetPort: 9090
