{{- if .Values.kubecostProductConfigs }}
{{- if .Values.kubecostProductConfigs.alertConfigs.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-configs
  labels:
    {{ include "cost-analyzer.commonLabels" . | nindent 4 }}
data:
  alerts.json: '{{ toJson .Values.kubecostProductConfigs.alertConfigs }}'
{{- end -}}
{{- end -}}
