{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress
spec:
  podSelector:
    matchLabels:
      app: cost-analyzer
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector: {}
{{- end -}}
