kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "cost-analyzer.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
    {{- if .Values.persistentVolume }}
      storage: {{ .Values.persistentVolume.size }}
    {{- else }}
      storage: 0.2Gi
    {{ end }}
