{{- if eq .Values.global.grafana.proxy false -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: external-grafana-config-map
data:
  grafanaURL: {{ .Values.global.grafana.scheme | default "http" }}://{{- .Values.global.grafana.domainName }}
{{- end -}}