{{- if .Values.clustercontroller }}
{{- if .Values.clustercontroller.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubecost.clusterControllerName" . }}
  labels:
    app: {{ template "kubecost.clusterControllerName" . }}
---
#
# NOTE: 
# The following ClusterRole permissions are only created and assigned for the 
# turndown feature. They will not be added to any clusters by default. 
#
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubecost.clusterControllerName" . }}
  labels:
    app: {{ template "kubecost.clusterControllerName" . }}
rules:
  - apiGroups:
      - kubecost.k8s.io
    resources:
      - turndownschedules
      - turndownschedules/status
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ""
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
      - patch
      - update
  - apiGroups:
      - ''
    resources:
      - deployments
      - nodes
      - pods
      - resourcequotas
      - replicationcontrollers
      - limitranges
      - pods/eviction
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - ''
    resources:
      - configmaps
      - namespaces
      - persistentvolumeclaims
      - persistentvolumes
      - endpoints
      - events
      - services
    verbs:
      - get 
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - deployments
      - daemonsets
      - replicasets
    verbs:
      - get 
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - get
      - list
      - watch
  - apiGroups: 
      - storage.k8s.io
    resources: 
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kubecost.clusterControllerName" . }}
  labels:
    app: {{ template "kubecost.clusterControllerName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kubecost.clusterControllerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kubecost.clusterControllerName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kubecost.clusterControllerName" . }}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "kubecost.clusterControllerName" . }}
  template:
    metadata:
      name: {{ template "kubecost.clusterControllerName" . }}
      labels:
        app: {{ template "kubecost.clusterControllerName" . }}
    spec:
      containers:
      - name: cluster-controller
        image: {{ .Values.clustercontroller.image }}
        imagePullPolicy: Always
        volumeMounts:
        - name: cluster-controller-keys
          mountPath: /var/keys
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/keys/service-key.json
        ports:
        - name: http-server
          containerPort: 9732
          hostPort: 9732
      serviceAccount: {{ template "kubecost.clusterControllerName" . }}
      serviceAccountName: {{ template "kubecost.clusterControllerName" . }}
      volumes:
      - name: cluster-controller-keys
        secret:
          secretName: cluster-controller-service-key
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kubecost.clusterControllerName" . }}-service
spec:
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9732
    targetPort: 9732
  selector:
    app: {{ template "kubecost.clusterControllerName" . }}
{{- end }}
{{- end }}
