dependencies:
  - name: prometheus
    repository: file//./charts/
    version: "7.X.X"
    condition: global.prometheus.enabled
  - name: grafana
    repository: file//./charts/
    version: "1.X.X"
    condition: global.grafana.enabled
