dependencies:
  - name: prometheus
    repository: file//./charts/
    version: "7.X.X"
    condition: prometheus.enabled
  - name: grafana
    repository: file//./charts/
    version: "1.X.X"
    condition: grafana.enabled
