global:

  prometheus:
    enabled: true # If false, Prometheus will not be installed
    fqdn: http://cost-analyzer-prometheus-server.default.svc.cluster.local #example fqdn. Ignored if enabled: true

  grafana:
    enabled: true # If false, Grafana will not be installed
    domainName: cost-analyzer-grafana.default.svc.cluster.local #example grafana domain Ignored if enabled: true

  notifications:
    slack: # Write to a webhook.
      enabled: false # Allow kubecost to write to your slackbot.
      webhook: https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX # Example Webhook
    alertmanager: # Supply an alertmanager FQDN to receive notifications from the app.
      enabled: false # If true, allow kubecost to write to your alertmanager
      fqdn: http://cost-analyzer-prometheus-server.default.svc.cluster.local #example fqdn. Ignored if prometheus.enabled: true

  podAnnotations: {}
    # iam.amazonaws.com/role: role-arn

kubecostChecks:
  image: "ajaytripathy/kubecost-checks"

kubecostFrontend:
  image: "ajaytripathy/kubecost-frontend"

kubecost:
  image: "ajaytripathy/kubecost"

kubecostModel:
  image: "ajaytripathy/kubecost-cost-model"

# If true, enable creation of NetworkPolicy resources.
networkPolicy:
  enabled: false
